import { MigrationInterface, QueryRunner } from "typeorm";

export class  $npmConfigName1790095113729 implements MigrationInterface {
    name = ' $npmConfigName1790095113729'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "stores" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" character varying, "name" character varying NOT NULL, "provider" character varying NOT NULL, "ownerName" character varying, "email" character varying NOT NULL, "phone" character varying, "language" character varying NOT NULL DEFAULT 'fr', "timezone" character varying NOT NULL DEFAULT 'Africa/Casablanca', "currency" character varying NOT NULL DEFAULT 'MAD', "settings" text, "status" character varying NOT NULL DEFAULT 'active', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "sessionId" uuid NOT NULL, CONSTRAINT "UQ_ee5b1dff8ad670443d1af9c2139" UNIQUE ("sessionId"), CONSTRAINT "REL_ee5b1dff8ad670443d1af9c213" UNIQUE ("sessionId"), CONSTRAINT "PK_7aa6e7d71fa7acdd7ca43d7c9cb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_stores_user" ON "stores"  ("userId") `);
        await queryRunner.query(`CREATE TABLE "sessions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" character varying, "name" character varying(100) NOT NULL, "displayName" character varying(50), "status" character varying(50) NOT NULL DEFAULT 'created', "phone" character varying(20), "pushName" character varying(100), "config" text NOT NULL DEFAULT '{}', "proxyUrl" character varying(255), "proxyType" character varying(10), "connectedAt" TIMESTAMP, "lastActiveAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_ac984ccbd8b01af155e1874e8cb" UNIQUE ("name"), CONSTRAINT "PK_3238ef96f18b355b671619111bc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_sessions_phone" ON "sessions"  ("phone") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_sessions_user_display_name" ON "sessions"  ("userId", "displayName") `);
        await queryRunner.query(`CREATE TABLE "baileys_stored_messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sessionId" uuid NOT NULL, "waMessageId" character varying NOT NULL, "serializedMessage" text NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e4bf6e9bd0372d95443f930822c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ae44b476c522450bd395615a7c" ON "baileys_stored_messages"  ("sessionId", "createdAt") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_1bb396e881628cd4dc8f0d2a8b" ON "baileys_stored_messages"  ("sessionId", "waMessageId") `);
        await queryRunner.query(`CREATE TABLE "lid_mappings" ("lid" character varying NOT NULL, "phone" character varying, "sessionId" character varying, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4f4ab6f955d63197b9e9c7cd3de" PRIMARY KEY ("lid"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1e39479a7a8aa37eab08df013b" ON "lid_mappings"  ("phone") `);
        await queryRunner.query(`CREATE TABLE "api_keys" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "keyHash" character varying(64) NOT NULL, "keyPrefix" character varying(12) NOT NULL, "role" character varying(20) NOT NULL DEFAULT 'operator', "allowedIps" text, "allowedSessions" text, "isActive" boolean NOT NULL DEFAULT true, "expiresAt" TIMESTAMP, "lastUsedAt" TIMESTAMP, "usageCount" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5c8a79801b44bd27b79228e1dad" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_df3b25181df0b4b59bd93f16e1" ON "api_keys"  ("keyHash") `);
        await queryRunner.query(`CREATE TABLE "user_accounts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(120) NOT NULL, "email" character varying(255) NOT NULL, "username" character varying(80) NOT NULL, "passwordHash" character varying(255) NOT NULL, "role" character varying(20) NOT NULL DEFAULT 'operator', "plan" character varying(20) DEFAULT 'free', "status" character varying(20) NOT NULL DEFAULT 'active', "settings" text, "sentMessages" integer NOT NULL DEFAULT '0', "receivedMessages" integer NOT NULL DEFAULT '0', "aiTokensUsed" integer NOT NULL DEFAULT '0', "audioTranscriptionsUsed" integer NOT NULL DEFAULT '0', "audioRepliesUsed" integer NOT NULL DEFAULT '0', "usagePeriodStart" TIMESTAMP NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_125e915cf23ad1cfb43815ce59b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_df3802ec9c31dd9491e3589378" ON "user_accounts"  ("email") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d45e7ca4a62293443961558c56" ON "user_accounts"  ("username") `);
        await queryRunner.query(`CREATE TABLE "user_login_sessions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tokenHash" character varying(64) NOT NULL, "userId" character varying NOT NULL, "expiresAt" TIMESTAMP NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_bea23845b0fb386a3679aebb72a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_0d7b4ddff9611d72076aef1acb" ON "user_login_sessions"  ("tokenHash") `);
        await queryRunner.query(`CREATE INDEX "IDX_1e4385ab45babf4bcc51aa85d4" ON "user_login_sessions"  ("userId") `);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "action" character varying(50) NOT NULL, "severity" character varying(10) NOT NULL DEFAULT 'info', "apiKeyId" character varying(36), "apiKeyName" character varying(100), "userId" character varying(36), "userName" character varying(120), "sessionId" character varying(36), "sessionName" character varying(100), "ipAddress" character varying(45), "userAgent" character varying(500), "method" character varying(10), "path" character varying(500), "statusCode" integer, "metadata" text, "errorMessage" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cee5459245f652b75eb2759b4c" ON "audit_logs"  ("action") `);
        await queryRunner.query(`CREATE INDEX "IDX_741fa976d1e04e695f3aa23cb8" ON "audit_logs"  ("apiKeyId") `);
        await queryRunner.query(`CREATE INDEX "IDX_cfa83f61e4d27a87fcae1e025a" ON "audit_logs"  ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_dd2b6e43c767b6b5b2bb227ace" ON "audit_logs"  ("sessionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c69efb19bf127c97e6740ad530" ON "audit_logs"  ("createdAt") `);
        await queryRunner.query(`CREATE TABLE "billing_config" ("id" character varying(20) NOT NULL DEFAULT 'default', "encryptedSettings" text NOT NULL, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8d8717f4e4172396323335e3803" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "billing_plans" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "slug" character varying(50) NOT NULL, "name" character varying(80) NOT NULL, "description" character varying(240) NOT NULL DEFAULT '', "priceMonthly" integer NOT NULL DEFAULT '0', "currency" character varying(3) NOT NULL DEFAULT 'USD', "limits" text NOT NULL, "features" text NOT NULL, "capabilities" text NOT NULL DEFAULT '{}', "trialDays" integer NOT NULL DEFAULT '0', "active" boolean NOT NULL DEFAULT true, "highlighted" boolean NOT NULL DEFAULT false, "sortOrder" integer NOT NULL DEFAULT '0', "stripePriceId" character varying(255), "paypalPlanId" character varying(255), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f5dd8c47fbdcd68a43b97f9795e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_1df145a154eeaabf30d43c5f74" ON "billing_plans"  ("slug") `);
        await queryRunner.query(`CREATE TABLE "billing_subscriptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "provider" character varying(20) NOT NULL, "providerCustomerId" character varying(255), "providerSubscriptionId" character varying(255), "status" character varying(40) NOT NULL DEFAULT 'pending', "planSlug" character varying(50) NOT NULL DEFAULT 'pro', "currentPeriodEnd" TIMESTAMP, "cancelAtPeriodEnd" boolean NOT NULL DEFAULT false, "planChangeStatus" character varying(30) NOT NULL DEFAULT 'none', "pendingPlanSlug" character varying(50), "planChangeEffectiveAt" TIMESTAMP, "planChangeRequestedAt" TIMESTAMP, "providerScheduleId" character varying(255), "planChangeError" character varying(500), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_da12bd094f95ed1a9ad21b0b2df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_59e19bfbcc389793e1beee1b84" ON "billing_subscriptions"  ("userId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_141bf25ec9232fb5cfbb8a909b" ON "billing_subscriptions"  ("provider", "providerSubscriptionId") `);
        await queryRunner.query(`CREATE TABLE "payment_transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "provider" character varying(20) NOT NULL, "providerEventId" character varying(255) NOT NULL, "providerPaymentId" character varying(255), "providerSubscriptionId" character varying(255), "parentTransactionId" uuid, "status" character varying(30) NOT NULL, "amount" integer NOT NULL DEFAULT '0', "currency" character varying(3) NOT NULL DEFAULT 'USD', "description" character varying(255), "paidAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d32b3c6b0d2c1d22604cbcc8c49" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_60b852936ca1e980cce98d977a" ON "payment_transactions"  ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_4b9fa5202c975489ee2e473fc0" ON "payment_transactions"  ("parentTransactionId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_2810888396d318ee075d307fef" ON "payment_transactions"  ("provider", "providerEventId") `);
        await queryRunner.query(`CREATE TABLE "webhook_delivery_failures" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "webhookId" character varying NOT NULL, "sessionId" character varying NOT NULL, "event" character varying NOT NULL, "url" character varying NOT NULL, "idempotencyKey" character varying, "deliveryId" character varying, "attempts" integer NOT NULL, "lastStatusCode" integer, "lastError" text NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e607f89c522fbdd9985610a96dd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_webhook_delivery_failures_sessionId" ON "webhook_delivery_failures"  ("sessionId") `);
        await queryRunner.query(`CREATE TABLE "webhooks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sessionId" uuid NOT NULL, "url" character varying(2048) NOT NULL, "events" text NOT NULL DEFAULT '["message.received"]', "secret" character varying(255), "headers" text NOT NULL DEFAULT '{}', "filters" text, "active" boolean NOT NULL DEFAULT true, "retryCount" integer NOT NULL DEFAULT '3', "lastTriggeredAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9e8795cfc899ab7bdaa831e8527" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_webhooks_sessionId" ON "webhooks"  ("sessionId") `);
        await queryRunner.query(`CREATE TABLE "message_batches" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "batch_id" character varying NOT NULL, "session_id" character varying NOT NULL, "status" character varying NOT NULL DEFAULT 'pending', "messages" text NOT NULL, "options" text, "progress" text, "results" text, "current_index" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "started_at" TIMESTAMP, "completed_at" TIMESTAMP, CONSTRAINT "UQ_message_batches_session_id_batch_id" UNIQUE ("session_id", "batch_id"), CONSTRAINT "PK_e69bcf640f4e7dd1350064b2e8b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sessionId" character varying NOT NULL, "waMessageId" character varying, "chatId" character varying NOT NULL, "chatName" character varying, "author" character varying, "from" character varying NOT NULL, "to" character varying NOT NULL, "body" text, "type" character varying NOT NULL DEFAULT 'text', "direction" character varying NOT NULL DEFAULT 'outgoing', "timestamp" bigint, "metadata" text, "status" character varying NOT NULL DEFAULT 'sent', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_18325f38ae6de43878487eff986" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_befd307485dbf0559d17e4a4d2" ON "messages"  ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_messages_createdAt" ON "messages"  ("createdAt") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_messages_sessionId_waMessageId" ON "messages"  ("sessionId", "waMessageId") `);
        await queryRunner.query(`CREATE INDEX "IDX_36bc604c820bb9adc4c75cd411" ON "messages"  ("chatId") `);
        await queryRunner.query(`CREATE INDEX "IDX_399833392126349ef0b04b9bed" ON "messages"  ("sessionId", "createdAt") `);
        await queryRunner.query(`CREATE TABLE "templates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sessionId" uuid NOT NULL, "name" character varying(100) NOT NULL, "body" text NOT NULL, "header" text, "footer" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_515948649ce0bbbe391de702ae5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_templates_session_name" ON "templates"  ("sessionId", "name") `);
        await queryRunner.query(`CREATE TABLE "conversation_mappings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sessionId" character varying NOT NULL, "chatId" character varying NOT NULL, "pluginId" character varying NOT NULL, "instanceId" character varying NOT NULL, "providerConversationId" character varying NOT NULL, "handoverState" character varying NOT NULL DEFAULT 'bot', "metadata" text, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e0e307f82d98260d64e7b840d9c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_conversation_mappings_reverse" ON "conversation_mappings"  ("pluginId", "instanceId", "providerConversationId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_conversation_mappings_forward" ON "conversation_mappings"  ("sessionId", "chatId", "pluginId", "instanceId") `);
        await queryRunner.query(`CREATE TABLE "ingress_events" ("id" character varying NOT NULL, "instanceId" character varying NOT NULL, "pluginId" character varying NOT NULL, "providerDeliveryId" character varying NOT NULL, "route" character varying NOT NULL, "payload" text, "payloadHash" character varying, "sessionId" character varying, "dispatchState" character varying, "dispatchAttempts" integer NOT NULL DEFAULT '0', "lastDispatchAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c4a752e069f001c4a34806f2538" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ingress_events_dispatchState" ON "ingress_events"  ("dispatchState", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_ingress_events_createdAt" ON "ingress_events"  ("createdAt") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_ingress_events_instance_delivery" ON "ingress_events"  ("pluginId", "instanceId", "providerDeliveryId") `);
        await queryRunner.query(`CREATE TABLE "integration_delivery_failures" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "direction" character varying NOT NULL, "pluginId" character varying NOT NULL, "instanceId" character varying NOT NULL, "sessionId" character varying, "deliveryId" character varying, "attempts" integer NOT NULL, "lastError" text NOT NULL, "payload" text, "redriven" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_bcb2ccba8bcfff0d53ce75790d7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_integration_delivery_failures_instance" ON "integration_delivery_failures"  ("pluginId", "instanceId") `);
        await queryRunner.query(`CREATE TABLE "plugin_instances" ("id" character varying NOT NULL, "pluginId" character varying NOT NULL, "instanceId" character varying NOT NULL, "sessionScope" character varying, "secret" character varying NOT NULL, "verifyToken" character varying, "config" text, "enabled" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1d261e16e830f63f75f2060863d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_plugin_instances_plugin_instance" ON "plugin_instances"  ("pluginId", "instanceId") `);
        await queryRunner.query(`CREATE TABLE "status_updates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sessionId" character varying NOT NULL, "contactJid" character varying NOT NULL, "contactName" character varying, "contactPushName" character varying, "waStatusId" character varying NOT NULL, "type" character varying NOT NULL, "caption" text, "mediaPath" character varying, "mediaMimetype" character varying, "mediaOmitted" boolean NOT NULL DEFAULT false, "omitReason" character varying, "backgroundColor" character varying, "font" integer, "postedAt" bigint NOT NULL, "expiresAt" bigint NOT NULL, CONSTRAINT "PK_a4dc636b9a35229ec5cee2b1dfb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_951ec734b350580529e0b7ab2d" ON "status_updates"  ("expiresAt") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_1152eee4d077ae74396d73c1fb" ON "status_updates"  ("sessionId", "waStatusId") `);
        await queryRunner.query(`CREATE INDEX "IDX_432ae5ea12bbda479dcae30fb1" ON "status_updates"  ("sessionId", "contactJid") `);
        await queryRunner.query(`CREATE TABLE "commerce_message_receipts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sessionId" character varying NOT NULL, "messageId" character varying(255) NOT NULL, "status" character varying(20) NOT NULL DEFAULT 'processing', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0dc7104c03884738c2c90f6951d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_f33e71eb0f77121cd4d86d044a" ON "commerce_message_receipts"  ("sessionId", "messageId") `);
        await queryRunner.query(`CREATE TABLE "commerce_tool_executions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "operationKey" character varying(255) NOT NULL, "storeId" character varying NOT NULL, "sessionId" character varying, "messageId" character varying(255), "customerPhone" character varying(40), "orderId" character varying, "provider" character varying(50) NOT NULL, "tool" character varying(80) NOT NULL, "status" character varying(20) NOT NULL DEFAULT 'started', "input" text, "result" text, "errorMessage" text, "durationMs" integer, "completedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f55ff777279c350d61c16fc71b6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8fb0f63585c59ccc58053b92db" ON "commerce_tool_executions"  ("storeId", "createdAt") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_86f8657421dcddd948ee275065" ON "commerce_tool_executions"  ("operationKey") `);
        await queryRunner.query(`CREATE TABLE "customer_support_conversations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sessionId" character varying(64) NOT NULL, "chatId" character varying(100) NOT NULL, "phone" character varying(40), "mode" character varying(20) NOT NULL DEFAULT 'ai', "issueStatus" character varying(20) NOT NULL DEFAULT 'open', "issueSummary" text, "priority" character varying(20) NOT NULL DEFAULT 'normal', "tags" text, "assignedUserId" character varying, "assignedAt" TIMESTAMP, "lastHumanMessageAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_bfa331ea6a43dccda69dbcc3106" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_bc178b8037fdad5d76b10f703b" ON "customer_support_conversations"  ("sessionId", "chatId") `);
        await queryRunner.query(`CREATE TABLE "order_ai_conversations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "orderId" uuid NOT NULL, "storeId" uuid NOT NULL, "status" character varying(40) NOT NULL DEFAULT 'active', "turnCount" integer NOT NULL DEFAULT '0', "turns" text, "lastError" text, "pendingAction" character varying(40), "pendingData" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_974995ae7a7eafbccb88d50127e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_1cd30c986a7cfad623a3b26212" ON "order_ai_conversations"  ("orderId") `);
        await queryRunner.query(`CREATE TABLE "orders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "storeId" uuid NOT NULL, "externalOrderId" character varying(100) NOT NULL, "orderNumber" character varying(100), "email" character varying(255), "phone" character varying(50), "customerName" character varying(255), "totalPrice" numeric(12,2) NOT NULL DEFAULT '0', "currency" character varying(10) NOT NULL DEFAULT 'USD', "financialStatus" character varying(50), "fulfillmentStatus" character varying(50), "lineItems" text, "shippingAddress" text, "customer" text, "tags" text, "status" character varying(50) NOT NULL DEFAULT 'open', "confirmationStatus" character varying(50) NOT NULL DEFAULT 'not_sent', "whatsappMessageId" character varying(100), "confirmationSentAt" TIMESTAMP, "confirmationError" text, "externalCreatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_710e2d4957aa5878dfe94e4ac2f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_6ccf223fb46d3694cf7072593d" ON "orders"  ("storeId", "externalOrderId") `);
        await queryRunner.query(`CREATE TABLE "products" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "storeId" uuid NOT NULL, "externalProductId" character varying(100) NOT NULL, "title" character varying(255) NOT NULL, "description" text, "handle" character varying(255), "productType" character varying(255), "vendor" character varying(255), "status" character varying(50) NOT NULL DEFAULT 'active', "tags" text, "imageUrl" text, "variants" text, "price" numeric(12,2) NOT NULL DEFAULT '0', "externalCreatedAt" TIMESTAMP NOT NULL DEFAULT now(), "externalUpdatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c93368fd5662c5c65bd67b129c" ON "products"  ("storeId", "externalProductId") `);
        await queryRunner.query(`CREATE TABLE "product_reviews" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "storeId" uuid NOT NULL, "orderId" uuid NOT NULL, "productId" uuid, "externalProductId" character varying(100) NOT NULL, "productName" character varying(255) NOT NULL, "customerPhone" character varying(50) NOT NULL, "rating" integer NOT NULL, "comment" character varying(1000), "status" character varying(30) NOT NULL DEFAULT 'published', "providerReviewId" character varying(100), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_67c1501aea1b0633ec441b00bd5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_6bcdc14d8e20a182ad5b48f1f1" ON "product_reviews"  ("orderId", "externalProductId", "customerPhone") `);
        await queryRunner.query(`CREATE TABLE "shopify_oauth_states" ("stateHash" character varying(64) NOT NULL, "storeId" character varying NOT NULL, "expiresAt" TIMESTAMP NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a8965f03da1802dbe05e09833e0" PRIMARY KEY ("stateHash"))`);
        await queryRunner.query(`CREATE TABLE "store_order_carts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "storeId" uuid NOT NULL, "phone" character varying(40) NOT NULL, "step" character varying(40) NOT NULL DEFAULT 'product', "productId" character varying, "variantId" character varying, "variantTitle" character varying, "quantity" integer NOT NULL DEFAULT '1', "customerName" character varying, "address1" text, "city" character varying, "postalCode" character varying, "country" character varying NOT NULL DEFAULT 'Morocco', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7bd9853af5f45b7af4732d0c511" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_0e176adc21006ae8effbf585d9" ON "store_order_carts"  ("storeId", "phone") `);
        await queryRunner.query(`CREATE TABLE "shopify_webhook_deliveries" ("webhookId" character varying(100) NOT NULL, "storeId" character varying, "topic" character varying(100) NOT NULL, "status" character varying(30) NOT NULL DEFAULT 'processing', "error" text, "attempts" integer NOT NULL DEFAULT '1', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_729d84fd1f3670a0426ce466b0f" PRIMARY KEY ("webhookId"))`);
        await queryRunner.query(`CREATE TABLE "campaigns" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" character varying NOT NULL, "sessionId" character varying NOT NULL, "name" character varying(120) NOT NULL, "message" text NOT NULL, "audienceType" character varying NOT NULL DEFAULT 'store_customers', "recipients" text NOT NULL, "batchIds" text NOT NULL, "status" character varying NOT NULL DEFAULT 'running', "riskScore" integer NOT NULL DEFAULT '0', "sent" integer NOT NULL DEFAULT '0', "failed" integer NOT NULL DEFAULT '0', "pending" integer NOT NULL DEFAULT '0', "skipped" integer NOT NULL DEFAULT '0', "completedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_831e3fcd4fc45b4e4c3f57a9ee4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_dc2c54425e991f2007a3a1ef3c" ON "campaigns"  ("userId", "createdAt") `);
        await queryRunner.query(`CREATE TABLE "youcan_oauth_states" ("stateHash" character varying(64) NOT NULL, "storeId" character varying NOT NULL, "expiresAt" TIMESTAMP NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_634b6e4fa183cfe82aa7ef4cff5" PRIMARY KEY ("stateHash"))`);
        await queryRunner.query(`CREATE TABLE "notification_reads" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "notificationId" character varying(36) NOT NULL, "userId" character varying(36) NOT NULL, "readAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c49ec541db45925cfb4e5c8dfbd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_38d077b9c1f597ae662c5ae411" ON "notification_reads"  ("notificationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_bddd24aed9c7f0beee6e8d8339" ON "notification_reads"  ("userId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_notification_reads_notification_user" ON "notification_reads"  ("notificationId", "userId") `);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" character varying(36), "createdByUserId" character varying(36) NOT NULL, "title" character varying(160) NOT NULL, "message" text NOT NULL, "kind" character varying(20) NOT NULL DEFAULT 'info', "link" character varying(500), "active" boolean NOT NULL DEFAULT true, "expiresAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_692a909ee0fa9383e7859f9b40" ON "notifications"  ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_831a5a06f879fb0bebf8965871" ON "notifications"  ("createdAt") `);
        await queryRunner.query(`ALTER TABLE "stores" ADD CONSTRAINT "FK_ee5b1dff8ad670443d1af9c2139" FOREIGN KEY ("sessionId") REFERENCES "sessions"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "baileys_stored_messages" ADD CONSTRAINT "FK_55c1dfd945d2c552a5313b25460" FOREIGN KEY ("sessionId") REFERENCES "sessions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "webhooks" ADD CONSTRAINT "FK_d209715bb62b12255e825580af6" FOREIGN KEY ("sessionId") REFERENCES "sessions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "templates" ADD CONSTRAINT "FK_53208331c90e332d3f13780729c" FOREIGN KEY ("sessionId") REFERENCES "sessions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_0f82354e5b05fd87884eff3a7b5" FOREIGN KEY ("storeId") REFERENCES "stores"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_782da5e50e94b763eb63225d69d" FOREIGN KEY ("storeId") REFERENCES "stores"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_reviews" ADD CONSTRAINT "FK_37b0fd0be2b97d977e03de4fa10" FOREIGN KEY ("storeId") REFERENCES "stores"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_reviews" ADD CONSTRAINT "FK_f1432cc7dde8c52ac11151d439e" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_reviews" ADD CONSTRAINT "FK_32edd80d91dff1bc19e79c8f16d" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "product_reviews" DROP CONSTRAINT "FK_32edd80d91dff1bc19e79c8f16d"`);
        await queryRunner.query(`ALTER TABLE "product_reviews" DROP CONSTRAINT "FK_f1432cc7dde8c52ac11151d439e"`);
        await queryRunner.query(`ALTER TABLE "product_reviews" DROP CONSTRAINT "FK_37b0fd0be2b97d977e03de4fa10"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_782da5e50e94b763eb63225d69d"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_0f82354e5b05fd87884eff3a7b5"`);
        await queryRunner.query(`ALTER TABLE "templates" DROP CONSTRAINT "FK_53208331c90e332d3f13780729c"`);
        await queryRunner.query(`ALTER TABLE "webhooks" DROP CONSTRAINT "FK_d209715bb62b12255e825580af6"`);
        await queryRunner.query(`ALTER TABLE "baileys_stored_messages" DROP CONSTRAINT "FK_55c1dfd945d2c552a5313b25460"`);
        await queryRunner.query(`ALTER TABLE "stores" DROP CONSTRAINT "FK_ee5b1dff8ad670443d1af9c2139"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_831a5a06f879fb0bebf8965871"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_692a909ee0fa9383e7859f9b40"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_notification_reads_notification_user"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bddd24aed9c7f0beee6e8d8339"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_38d077b9c1f597ae662c5ae411"`);
        await queryRunner.query(`DROP TABLE "notification_reads"`);
        await queryRunner.query(`DROP TABLE "youcan_oauth_states"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dc2c54425e991f2007a3a1ef3c"`);
        await queryRunner.query(`DROP TABLE "campaigns"`);
        await queryRunner.query(`DROP TABLE "shopify_webhook_deliveries"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0e176adc21006ae8effbf585d9"`);
        await queryRunner.query(`DROP TABLE "store_order_carts"`);
        await queryRunner.query(`DROP TABLE "shopify_oauth_states"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6bcdc14d8e20a182ad5b48f1f1"`);
        await queryRunner.query(`DROP TABLE "product_reviews"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c93368fd5662c5c65bd67b129c"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6ccf223fb46d3694cf7072593d"`);
        await queryRunner.query(`DROP TABLE "orders"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1cd30c986a7cfad623a3b26212"`);
        await queryRunner.query(`DROP TABLE "order_ai_conversations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bc178b8037fdad5d76b10f703b"`);
        await queryRunner.query(`DROP TABLE "customer_support_conversations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_86f8657421dcddd948ee275065"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8fb0f63585c59ccc58053b92db"`);
        await queryRunner.query(`DROP TABLE "commerce_tool_executions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f33e71eb0f77121cd4d86d044a"`);
        await queryRunner.query(`DROP TABLE "commerce_message_receipts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_432ae5ea12bbda479dcae30fb1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1152eee4d077ae74396d73c1fb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_951ec734b350580529e0b7ab2d"`);
        await queryRunner.query(`DROP TABLE "status_updates"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_plugin_instances_plugin_instance"`);
        await queryRunner.query(`DROP TABLE "plugin_instances"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_integration_delivery_failures_instance"`);
        await queryRunner.query(`DROP TABLE "integration_delivery_failures"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_ingress_events_instance_delivery"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ingress_events_createdAt"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ingress_events_dispatchState"`);
        await queryRunner.query(`DROP TABLE "ingress_events"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_conversation_mappings_forward"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_conversation_mappings_reverse"`);
        await queryRunner.query(`DROP TABLE "conversation_mappings"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_templates_session_name"`);
        await queryRunner.query(`DROP TABLE "templates"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_399833392126349ef0b04b9bed"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_36bc604c820bb9adc4c75cd411"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_messages_sessionId_waMessageId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_messages_createdAt"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_befd307485dbf0559d17e4a4d2"`);
        await queryRunner.query(`DROP TABLE "messages"`);
        await queryRunner.query(`DROP TABLE "message_batches"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_webhooks_sessionId"`);
        await queryRunner.query(`DROP TABLE "webhooks"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_webhook_delivery_failures_sessionId"`);
        await queryRunner.query(`DROP TABLE "webhook_delivery_failures"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2810888396d318ee075d307fef"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4b9fa5202c975489ee2e473fc0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_60b852936ca1e980cce98d977a"`);
        await queryRunner.query(`DROP TABLE "payment_transactions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_141bf25ec9232fb5cfbb8a909b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_59e19bfbcc389793e1beee1b84"`);
        await queryRunner.query(`DROP TABLE "billing_subscriptions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1df145a154eeaabf30d43c5f74"`);
        await queryRunner.query(`DROP TABLE "billing_plans"`);
        await queryRunner.query(`DROP TABLE "billing_config"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c69efb19bf127c97e6740ad530"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dd2b6e43c767b6b5b2bb227ace"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cfa83f61e4d27a87fcae1e025a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_741fa976d1e04e695f3aa23cb8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cee5459245f652b75eb2759b4c"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1e4385ab45babf4bcc51aa85d4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0d7b4ddff9611d72076aef1acb"`);
        await queryRunner.query(`DROP TABLE "user_login_sessions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d45e7ca4a62293443961558c56"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_df3802ec9c31dd9491e3589378"`);
        await queryRunner.query(`DROP TABLE "user_accounts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_df3b25181df0b4b59bd93f16e1"`);
        await queryRunner.query(`DROP TABLE "api_keys"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1e39479a7a8aa37eab08df013b"`);
        await queryRunner.query(`DROP TABLE "lid_mappings"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1bb396e881628cd4dc8f0d2a8b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ae44b476c522450bd395615a7c"`);
        await queryRunner.query(`DROP TABLE "baileys_stored_messages"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_sessions_user_display_name"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_sessions_phone"`);
        await queryRunner.query(`DROP TABLE "sessions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_stores_user"`);
        await queryRunner.query(`DROP TABLE "stores"`);
    }

}
