import { useEffect, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { CheckCircle2, CreditCard, Globe2, History, ShieldCheck, WalletCards } from 'lucide-react';
import { PageHeader } from '../components/PageHeader';
import { adminBillingApi } from '../services/api';
import './Account.css';

type PaymentTab = 'overview' | 'general' | 'stripe' | 'paypal';

export function PaymentSettings() {
  const client = useQueryClient();
  const [tab, setTab] = useState<PaymentTab>('overview');
  const [filters, setFilters] = useState({ provider: '', status: '', from: '', to: '', search: '', page: 1 });
  const { data, isLoading } = useQuery({ queryKey: ['admin', 'billing-settings'], queryFn: adminBillingApi.get });
  const [form, setForm] = useState<Record<string, any>>({ stripeEnabled: false, paypalEnabled: false, paypalEnvironment: 'sandbox' });
  const { data: history, isLoading: historyLoading } = useQuery({ queryKey: ['admin', 'billing-history', filters], queryFn: () => adminBillingApi.history({ ...filters, limit: 20 }) });
  const { data: subscriptions = [] } = useQuery({ queryKey: ['admin', 'billing-subscriptions'], queryFn: () => adminBillingApi.subscriptions() });
  useEffect(() => { if (data) setForm(current => ({ ...current, publicAppUrl: data.publicAppUrl ?? '', stripeEnabled: data.stripeEnabled, paypalEnabled: data.paypalEnabled, paypalEnvironment: data.paypalEnvironment })); }, [data]);
  const save = useMutation({ mutationFn: () => adminBillingApi.update(form), onSuccess: () => void client.invalidateQueries({ queryKey: ['admin', 'billing-settings'] }) });
  const paymentAction = useMutation({
    mutationFn: async (input: { type: 'refund' | 'cancel' | 'reactivate'; id: string; amount?: number; immediate?: boolean }) => input.type === 'refund' ? adminBillingApi.refund(input.id, input.amount, 'Refunded by administrator') : input.type === 'cancel' ? adminBillingApi.cancelSubscription(input.id, Boolean(input.immediate), 'Cancelled by administrator') : adminBillingApi.reactivateSubscription(input.id),
    onSuccess: () => { void client.invalidateQueries({ queryKey: ['admin', 'billing-history'] }); void client.invalidateQueries({ queryKey: ['admin', 'billing-subscriptions'] }); void client.invalidateQueries({ queryKey: ['admin', 'users'] }); },
  });
  const field = (key: string, label: string, hint: string, secret = false) => <label className="payment-field"><span>{label}</span><input type={secret ? 'password' : 'text'} value={form[key] ?? ''} placeholder={secret && data?.configured[key] ? 'Configured — leave blank to keep current value' : ''} onChange={event => setForm({ ...form, [key]: event.target.value })}/><small>{hint}</small></label>;
  const configuredCount = data ? Object.values(data.configured).filter(Boolean).length : 0;
  return <div className="account-page payment-settings-page">
    <PageHeader title="Payment settings" subtitle="Manage provider credentials, subscriptions, and checkout configuration" />
    <div className="payment-overview"><div><ShieldCheck size={20}/><span><strong>Encrypted storage</strong><small>Secrets are protected at rest</small></span></div><div><CheckCircle2 size={20}/><span><strong>{configuredCount} credentials</strong><small>Currently configured</small></span></div><div><CreditCard size={20}/><span><strong>$5 / month</strong><small>Pro subscription price</small></span></div></div>
    <div className="payment-layout">
      <nav className="payment-tabs"><button type="button" className={tab === 'overview' ? 'active' : ''} onClick={() => setTab('overview')}><History size={18}/><span>Payments<small>Revenue and history</small></span></button><button type="button" className={tab === 'general' ? 'active' : ''} onClick={() => setTab('general')}><Globe2 size={18}/><span>General<small>Public checkout URL</small></span></button><button type="button" className={tab === 'stripe' ? 'active' : ''} onClick={() => setTab('stripe')}><CreditCard size={18}/><span>Stripe<small>{data?.stripeEnabled ? 'Enabled' : 'Disabled'}</small></span></button><button type="button" className={tab === 'paypal' ? 'active' : ''} onClick={() => setTab('paypal')}><WalletCards size={18}/><span>PayPal<small>{data?.paypalEnabled ? 'Enabled' : 'Disabled'}</small></span></button></nav>
      {tab === 'overview' ? <section className="payment-admin-overview">
        <div className="payment-stat-grid"><div><small>Net earnings</small><strong>{history?.summary.earnings.map(item => new Intl.NumberFormat(undefined, { style: 'currency', currency: item.currency }).format(item.amount / 100)).join(' · ') || '$0.00'}</strong></div><div><small>Active subscribers</small><strong>{history?.summary.activeSubscribers ?? 0}</strong></div><div><small>Successful</small><strong>{history?.summary.successful ?? 0}</strong></div><div><small>Failed</small><strong>{history?.summary.failed ?? 0}</strong></div></div>
        <div className="payment-filters"><input placeholder="Payment or subscription ID" value={filters.search} onChange={e => setFilters({ ...filters, search: e.target.value, page: 1 })}/><select value={filters.provider} onChange={e => setFilters({ ...filters, provider: e.target.value, page: 1 })}><option value="">All providers</option><option value="stripe">Stripe</option><option value="paypal">PayPal</option></select><select value={filters.status} onChange={e => setFilters({ ...filters, status: e.target.value, page: 1 })}><option value="">All statuses</option><option value="succeeded">Succeeded</option><option value="failed">Failed</option><option value="refunded">Refunded</option><option value="pending">Pending</option></select><input type="date" value={filters.from} onChange={e => setFilters({ ...filters, from: e.target.value, page: 1 })}/><input type="date" value={filters.to} onChange={e => setFilters({ ...filters, to: e.target.value, page: 1 })}/></div>
        <div className="payment-table-wrap"><table className="payment-table"><thead><tr><th>Date</th><th>Subscriber</th><th>Provider</th><th>Status</th><th>Amount</th><th>Action</th></tr></thead><tbody>{history?.items.map(payment => <tr key={payment.id}><td>{new Date(payment.paidAt ?? payment.createdAt).toLocaleString()}</td><td><strong>{payment.user?.name ?? 'Unknown'}</strong><small>{payment.user?.email}</small></td><td className="payment-provider">{payment.provider}</td><td><span className={`payment-status ${payment.status}`}>{payment.status}</span></td><td>{new Intl.NumberFormat(undefined, { style: 'currency', currency: payment.currency }).format(payment.amount / 100)}{payment.refundedAmount > 0 && <small>Refunded: {new Intl.NumberFormat(undefined, { style: 'currency', currency: payment.currency }).format(payment.refundedAmount / 100)}</small>}</td><td>{payment.status === 'succeeded' && payment.refundedAmount < payment.amount && <button className="table-action danger" disabled={paymentAction.isPending} onClick={() => { const value = window.prompt(`Refund amount in ${payment.currency}. Leave empty for the full remaining amount.`); if (value === null) return; const amount = value.trim() ? Math.round(Number(value) * 100) : undefined; if (value.trim() && (!Number.isFinite(amount) || Number(amount) <= 0)) return window.alert('Enter a valid positive amount.'); if (window.confirm('This sends a real refund to the customer. Continue?')) paymentAction.mutate({ type: 'refund', id: payment.id, amount }); }}>Refund</button>}</td></tr>)}{!historyLoading && !history?.items.length && <tr><td colSpan={6} className="payment-empty">No payments match these filters.</td></tr>}</tbody></table></div>
        <div className="payment-pagination"><button disabled={filters.page <= 1} onClick={() => setFilters({ ...filters, page: filters.page - 1 })}>Previous</button><span>Page {filters.page} · {history?.total ?? 0} results</span><button disabled={filters.page * 20 >= (history?.total ?? 0)} onClick={() => setFilters({ ...filters, page: filters.page + 1 })}>Next</button></div>
        <div className="payment-history-heading"><div><h2>Subscriptions</h2><p>Manage renewal and access for every subscriber.</p></div><strong>{subscriptions.length} records</strong></div>
        <div className="payment-table-wrap"><table className="payment-table"><thead><tr><th>Customer</th><th>Provider</th><th>Status</th><th>Period end</th><th>Actions</th></tr></thead><tbody>{subscriptions.map(subscription => <tr key={subscription.id}><td><strong>{subscription.user?.name ?? 'Unknown'}</strong><small>{subscription.user?.email}</small></td><td className="payment-provider">{subscription.provider}</td><td><span className={`payment-status ${subscription.status}`}>{subscription.cancelAtPeriodEnd ? 'cancelling' : subscription.status}</span></td><td>{subscription.currentPeriodEnd ? new Date(subscription.currentPeriodEnd).toLocaleDateString() : '—'}</td><td className="table-actions">{subscription.cancelAtPeriodEnd && subscription.provider === 'stripe' ? <button className="table-action" disabled={paymentAction.isPending} onClick={() => paymentAction.mutate({ type: 'reactivate', id: subscription.id })}>Reactivate</button> : ['active', 'trialing'].includes(subscription.status.toLowerCase()) && <><button className="table-action danger" disabled={paymentAction.isPending} onClick={() => { if (window.confirm(subscription.provider === 'paypal' ? 'PayPal cancellation is immediate. Continue?' : 'Schedule cancellation at period end?')) paymentAction.mutate({ type: 'cancel', id: subscription.id }); }}>Cancel renewal</button>{subscription.provider === 'stripe' && <button className="table-action danger subtle" disabled={paymentAction.isPending} onClick={() => { if (window.confirm('Cancel immediately? The user loses Pro access now. This does not automatically refund them.')) paymentAction.mutate({ type: 'cancel', id: subscription.id, immediate: true }); }}>Cancel now</button>}</>}</td></tr>)}{!subscriptions.length && <tr><td colSpan={5} className="payment-empty">No subscriptions found.</td></tr>}</tbody></table></div>
        {paymentAction.isError && <div className="billing-error">{paymentAction.error.message}</div>}
      </section> :
      <form className="account-card payment-panel" onSubmit={event => { event.preventDefault(); save.mutate(); }}>
        {isLoading ? <p>Loading payment settings…</p> : <>
          {tab === 'general' && <><div className="payment-panel-title"><Globe2/><div><h2>General configuration</h2><p>Used for checkout success, cancellation, and billing portal redirects.</p></div></div>{field('publicAppUrl', 'Public dashboard URL', 'Example: https://app.yourdomain.com')}</>}
          {tab === 'stripe' && <><div className="payment-panel-title"><CreditCard/><div><h2>Stripe</h2><p>Recurring Pro subscriptions through Stripe Checkout.</p></div></div><label className="provider-toggle"><span><strong>Enable Stripe payments</strong><small>Allow customers to subscribe using Stripe</small></span><input type="checkbox" checked={Boolean(form.stripeEnabled)} onChange={event => setForm({ ...form, stripeEnabled: event.target.checked })}/></label>{field('stripeSecretKey', 'Secret key', 'Starts with sk_test_ or sk_live_', true)}{field('stripePriceId', 'Pro monthly Price ID', 'The recurring $5/month Stripe Price identifier')}{field('stripeWebhookSecret', 'Webhook signing secret', 'Used to verify incoming Stripe events', true)}</>}
          {tab === 'paypal' && <><div className="payment-panel-title"><WalletCards/><div><h2>PayPal</h2><p>Recurring Pro subscriptions through PayPal Billing.</p></div></div><label className="provider-toggle"><span><strong>Enable PayPal payments</strong><small>Allow customers to subscribe using PayPal</small></span><input type="checkbox" checked={Boolean(form.paypalEnabled)} onChange={event => setForm({ ...form, paypalEnabled: event.target.checked })}/></label><label className="payment-field"><span>Environment</span><select value={form.paypalEnvironment} onChange={event => setForm({ ...form, paypalEnvironment: event.target.value })}><option value="sandbox">Sandbox — testing</option><option value="live">Live — real payments</option></select><small>Use sandbox until your payment flow is fully tested.</small></label>{field('paypalClientId', 'Client ID', 'PayPal REST application client identifier', true)}{field('paypalClientSecret', 'Client secret', 'PayPal REST application secret', true)}{field('paypalPlanId', 'Pro monthly Plan ID', 'The recurring $5/month PayPal plan identifier')}{field('paypalWebhookId', 'Webhook ID', 'Used to verify incoming PayPal events', true)}</>}
        </>}
        <div className="payment-save"><button className="account-primary" disabled={save.isPending || isLoading}>{save.isPending ? 'Saving…' : 'Save settings'}</button>{save.isSuccess && <span className="account-success">Settings saved securely.</span>}{save.isError && <span className="billing-error">{save.error.message}</span>}</div>
      </form>
      }
    </div>
  </div>;
}
