// import { Injectable } from '@nestjs/common';
// import PDFDocument = require('pdfkit');
// import { Order } from '../../stores/entities/order.entity';
// import { Store } from '../../stores/entities/store.entity';

// @Injectable()
// export class OrderReportService {
//   async customerOrders(store: Store, orders: Order[]): Promise<Buffer> {
//     const document = new PDFDocument({ size: 'A4', margin: 48, info: { Title: `${store.name} order history`, Author: 'SmartConfirm' } });
//     const chunks: Buffer[] = [];
//     document.on('data', chunk => chunks.push(Buffer.from(chunk)));
//     const complete = new Promise<Buffer>((resolve, reject) => {
//       document.on('end', () => resolve(Buffer.concat(chunks)));
//       document.on('error', reject);
//     });
//     document.font('Helvetica-Bold').fontSize(22).fillColor('#111827').text(store.name);
//     document.font('Helvetica').fontSize(10).fillColor('#6b7280').text('Customer order history');
//     document.moveDown(0.5).strokeColor('#22c55e').lineWidth(2).moveTo(48, document.y).lineTo(547, document.y).stroke();
//     document.moveDown();
//     let grandTotal = 0;
//     for (const order of orders) {
//       if (document.y > 690) document.addPage();
//       document.font('Helvetica-Bold').fontSize(13).fillColor('#111827').text(`Order ${order.orderNumber ?? order.externalOrderId}`);
//       document.font('Helvetica').fontSize(9).fillColor('#4b5563').text(`Status: ${order.status}  |  Payment: ${order.financialStatus ?? '-'}  |  Delivery: ${order.fulfillmentStatus ?? '-'}`);
//       for (const item of order.lineItems ?? []) {
//         const name = String(item.title ?? item.name ?? 'Product').replace(/[^\x20-\x7E\xA0-\xFF]/g, '?');
//         document.text(`${Number(item.quantity ?? 1)} x ${name}`);
//       }
//       document.font('Helvetica-Bold').text(`Total: ${Number(order.totalPrice).toFixed(2)} ${order.currency}`);
//       document.moveDown().strokeColor('#e5e7eb').lineWidth(1).moveTo(48, document.y).lineTo(547, document.y).stroke().moveDown();
//       grandTotal += Number(order.totalPrice) || 0;
//     }
//     document.font('Helvetica-Bold').fontSize(14).fillColor('#111827').text(`Orders: ${orders.length}`);
//     if (new Set(orders.map(order => order.currency)).size === 1 && orders[0]) document.text(`Combined total: ${grandTotal.toFixed(2)} ${orders[0].currency}`);
//     document.font('Helvetica').fontSize(8).fillColor('#9ca3af').text(`Generated by SmartConfirm - ${new Date().toISOString()}`, 48, 790, { align: 'center', width: 499 });
//     document.end();
//     return complete;
//   }
// }
import { Injectable } from '@nestjs/common';
import PDFDocument = require('pdfkit');
import { Order } from '../../stores/entities/order.entity';
import { Store } from '../../stores/entities/store.entity';

const COLORS = {
  text: '#111827',
  muted: '#6b7280',
  faint: '#9ca3af',
  border: '#e5e7eb',
  headerBg: '#111827',
  headerText: '#ffffff',
  rowAlt: '#f9fafb',
  accent: '#22c55e',
  statusOk: '#16a34a',
  statusWarn: '#d97706',
  statusBad: '#dc2626',
};

const PAGE_MARGIN = 48;
const CONTENT_LEFT = PAGE_MARGIN;
const CONTENT_RIGHT = 547; // A4 width (595.28) - margin
const CONTENT_WIDTH = CONTENT_RIGHT - CONTENT_LEFT;
const FOOTER_Y = 800;
const CONTENT_BOTTOM = 760; // reserve room for footer

interface Column {
  key: string;
  label: string;
  width: number;
  align?: 'left' | 'right' | 'center';
}

@Injectable()
export class OrderReportService {
  async customerOrders(store: Store, orders: Order[]): Promise<Buffer> {
    const document = new PDFDocument({
      size: 'A4',
      margin: PAGE_MARGIN,
      bufferPages: true,
      info: { Title: `${store.name} order history`, Author: 'SmartConfirm' },
    });

    const chunks: Buffer[] = [];
    document.on('data', (chunk) => chunks.push(Buffer.from(chunk)));
    const complete = new Promise<Buffer>((resolve, reject) => {
      document.on('end', () => resolve(Buffer.concat(chunks)));
      document.on('error', reject);
    });

    const customer = orders[0] ?? null;

    this.drawInvoiceHeader(document, store, customer, orders);
    this.drawOrdersTable(document, store, orders);
    this.drawSummary(document, orders);

    this.stampFooters(document, store);
    document.end();
    return complete;
  }

  // ---------- Header ----------

  private drawInvoiceHeader(document: PDFKit.PDFDocument, store: Store, customer: Order | null, orders: Order[]) {
    let y = PAGE_MARGIN;

    document.font('Helvetica-Bold').fontSize(20).fillColor(COLORS.text).text(store.name, CONTENT_LEFT, y);
    document
      .font('Helvetica')
      .fontSize(9)
      .fillColor(COLORS.muted)
      .text('Customer order history', CONTENT_LEFT, y + 24);

    document
      .font('Helvetica-Bold')
      .fontSize(16)
      .fillColor(COLORS.text)
      .text('ORDER HISTORY', CONTENT_LEFT, y, { width: CONTENT_WIDTH, align: 'right' });
    document
      .font('Helvetica')
      .fontSize(9)
      .fillColor(COLORS.muted)
      .text(`Generated ${new Date().toLocaleDateString('en-GB')}`, CONTENT_LEFT, y + 20, {
        width: CONTENT_WIDTH,
        align: 'right',
      });

    y += 48;
    document.strokeColor(COLORS.accent).lineWidth(2).moveTo(CONTENT_LEFT, y).lineTo(CONTENT_RIGHT, y).stroke();
    y += 20;

    const colWidth = CONTENT_WIDTH / 2 - 12;
    const leftX = CONTENT_LEFT;
    const rightX = CONTENT_LEFT + CONTENT_WIDTH / 2 + 12;

    document.font('Helvetica-Bold').fontSize(9).fillColor(COLORS.muted).text('FROM', leftX, y);
    document.font('Helvetica-Bold').fontSize(9).fillColor(COLORS.muted).text('BILL TO', rightX, y);
    y += 14;

    const storeLines = [store.name, store.email, store.phone].filter(Boolean) as string[];
    const customerLines = customer
      ? ([
          customer.customerName,
          customer.email,
          customer.phone,
          this.formatAddress(customer.shippingAddress),
        ].filter(Boolean) as string[])
      : ['—'];

    const linesToRender = Math.max(storeLines.length, customerLines.length);
    document.font('Helvetica').fontSize(10).fillColor(COLORS.text);
    for (let i = 0; i < linesToRender; i++) {
      if (storeLines[i]) document.text(storeLines[i], leftX, y, { width: colWidth });
      if (customerLines[i]) document.text(customerLines[i], rightX, y, { width: colWidth });
      y += 14;
    }

    y += 10;
    document.strokeColor(COLORS.border).lineWidth(1).moveTo(CONTENT_LEFT, y).lineTo(CONTENT_RIGHT, y).stroke();
    document.y = y + 16;
  }

  private formatAddress(addr: Record<string, any> | null): string | null {
    if (!addr) return null;
    const parts = [addr.address1, addr.city, addr.province, addr.zip, addr.country].filter(Boolean);
    return parts.length ? parts.join(', ') : null;
  }

  // ---------- Orders table ----------

  private drawOrdersTable(document: PDFKit.PDFDocument, store: Store, orders: Order[]) {
    for (const order of orders) {
      this.ensureSpace(document, store, 70);
      this.drawOrderCard(document, store, order);
      document.moveDown(0.6);
    }
  }

  private drawOrderCard(document: PDFKit.PDFDocument, store: Store, order: Order) {
    const startY = document.y;

    // Order title row
    document
      .font('Helvetica-Bold')
      .fontSize(12)
      .fillColor(COLORS.text)
      .text(`Order ${order.orderNumber ?? order.externalOrderId}`, CONTENT_LEFT, startY);

    const statusColor = this.statusColor(order.status);
    document
      .font('Helvetica-Bold')
      .fontSize(8)
      .fillColor(statusColor)
      .text(order.status?.toUpperCase() ?? '-', CONTENT_LEFT, startY + 2, { width: CONTENT_WIDTH, align: 'right' });

    document
      .font('Helvetica')
      .fontSize(8)
      .fillColor(COLORS.muted)
      .text(
        `Payment: ${order.financialStatus ?? '-'}   |   Delivery: ${order.fulfillmentStatus ?? '-'}   |   Date: ${this.formatDate(order.externalCreatedAt)}`,
        CONTENT_LEFT,
        startY + 16,
      );

    document.y = startY + 32;

    const columns: Column[] = [
      { key: 'item', label: 'ITEM', width: 289, align: 'left' },
      { key: 'qty', label: 'QTY', width: 50, align: 'center' },
      { key: 'unit', label: 'UNIT PRICE', width: 80, align: 'right' },
      { key: 'total', label: 'AMOUNT', width: 80, align: 'right' },
    ];

    this.drawTableHeader(document, columns);

    const items = order.lineItems ?? [];
    let orderSubtotal = 0;
    items.forEach((item, idx) => {
      this.ensureSpace(document, store, 20, () => this.drawTableHeader(document, columns));

      const qty = Number(item.quantity ?? 1);
      const unitPrice = Number(item.price ?? item.unitPrice ?? 0);
      const lineTotal = unitPrice ? unitPrice * qty : Number(item.total ?? 0);
      orderSubtotal += lineTotal;

      const name = String(item.title ?? item.name ?? 'Product').replace(/[^\x20-\x7E\xA0-\xFF]/g, '?');
      this.drawTableRow(
        document,
        columns,
        {
          item: name,
          qty: String(qty),
          unit: unitPrice ? this.money(unitPrice, order.currency) : '-',
          total: this.money(lineTotal || Number(order.totalPrice), order.currency),
        },
        idx % 2 === 1,
      );
    });

    // Order total line
    const total = Number(order.totalPrice) || orderSubtotal;
    const y = document.y + 4;
    document.strokeColor(COLORS.border).lineWidth(1).moveTo(CONTENT_LEFT, y).lineTo(CONTENT_RIGHT, y).stroke();
    document
      .font('Helvetica-Bold')
      .fontSize(10)
      .fillColor(COLORS.text)
      .text('Order total', CONTENT_LEFT, y + 8, { width: CONTENT_WIDTH - 90 });
    document
      .font('Helvetica-Bold')
      .fontSize(10)
      .fillColor(COLORS.text)
      .text(this.money(total, order.currency), CONTENT_LEFT + CONTENT_WIDTH - 90, y + 8, {
        width: 90,
        align: 'right',
      });
    document.y = y + 24;
  }

  private drawTableHeader(document: PDFKit.PDFDocument, columns: Column[]) {
    const y = document.y;
    document.rect(CONTENT_LEFT, y, CONTENT_WIDTH, 18).fill(COLORS.headerBg);
    let x = CONTENT_LEFT;
    document.font('Helvetica-Bold').fontSize(8).fillColor(COLORS.headerText);
    for (const col of columns) {
      document.text(col.label, x + 6, y + 5, { width: col.width - 10, align: col.align ?? 'left' });
      x += col.width;
    }
    document.y = y + 18;
  }

  private drawTableRow(document: PDFKit.PDFDocument, columns: Column[], values: Record<string, string>, shaded: boolean) {
    const rowHeight = 18;
    const y = document.y;
    if (shaded) document.rect(CONTENT_LEFT, y, CONTENT_WIDTH, rowHeight).fill(COLORS.rowAlt);

    let x = CONTENT_LEFT;
    document.font('Helvetica').fontSize(9).fillColor(COLORS.text);
    for (const col of columns) {
      document.text(values[col.key] ?? '-', x + 6, y + 4, { width: col.width - 10, align: col.align ?? 'left' });
      x += col.width;
    }
    document.y = y + rowHeight;
  }

  private statusColor(status?: string): string {
    const s = (status ?? '').toLowerCase();
    if (['completed', 'confirmed', 'paid', 'delivered'].includes(s)) return COLORS.statusOk;
    if (['cancelled', 'failed', 'refused'].includes(s)) return COLORS.statusBad;
    return COLORS.statusWarn;
  }

  // ---------- Summary ----------

  private drawSummary(document: PDFKit.PDFDocument, orders: Order[]) {
    this.ensureSpace(document, undefined as any, 80);

    const byCurrency = new Map<string, number>();
    for (const order of orders) {
      const cur = order.currency ?? 'USD';
      byCurrency.set(cur, (byCurrency.get(cur) ?? 0) + (Number(order.totalPrice) || 0));
    }

    const y = document.y + 8;
    document.strokeColor(COLORS.accent).lineWidth(2).moveTo(CONTENT_LEFT, y).lineTo(CONTENT_RIGHT, y).stroke();

    const boxX = CONTENT_RIGHT - 220;
    let cursorY = y + 12;

    document
      .font('Helvetica')
      .fontSize(10)
      .fillColor(COLORS.muted)
      .text('Total orders', boxX, cursorY, { width: 130 });
    document
      .font('Helvetica-Bold')
      .fontSize(10)
      .fillColor(COLORS.text)
      .text(String(orders.length), boxX + 130, cursorY, { width: 90, align: 'right' });
    cursorY += 16;

    for (const [currency, total] of byCurrency) {
      document
        .font('Helvetica')
        .fontSize(10)
        .fillColor(COLORS.muted)
        .text(`Combined total (${currency})`, boxX, cursorY, { width: 130 });
      document
        .font('Helvetica-Bold')
        .fontSize(12)
        .fillColor(COLORS.text)
        .text(this.money(total, currency), boxX + 100, cursorY - 1, { width: 120, align: 'right' });
      cursorY += 20;
    }

    document.y = cursorY;
  }

  // ---------- Layout helpers ----------

  private ensureSpace(
    document: PDFKit.PDFDocument,
    store: Store | undefined,
    needed: number,
    onNewPage?: () => void,
  ) {
    if (document.y + needed > CONTENT_BOTTOM) {
      document.addPage();
      document.y = PAGE_MARGIN;
      if (onNewPage) onNewPage();
    }
  }

  private stampFooters(document: PDFKit.PDFDocument, store: Store) {
    const range = document.bufferedPageRange();
    for (let i = range.start; i < range.start + range.count; i++) {
      document.switchToPage(i);
      document
        .font('Helvetica')
        .fontSize(8)
        .fillColor(COLORS.faint)
        .text(
          `${store.name} - Generated by SmartConfirm - ${new Date().toISOString()}   |   Page ${i + 1} of ${range.count}`,
          CONTENT_LEFT,
          FOOTER_Y,
          { align: 'center', width: CONTENT_WIDTH },
        );
    }
  }

  private money(amount: number, currency: string): string {
    return `${(amount || 0).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })} ${currency}`;
  }

  private formatDate(date: Date | null): string {
    if (!date) return '-';
    return new Date(date).toLocaleDateString('en-GB');
  }
}